#!/bin/sh
#
# @name Gazebo hillstar
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=hillstar}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

param set-default COM_DISARM_PRFLT -1

param set-default CA_AIRFRAME 13	# custom_tilting_multirotors
param set-default CA_TILTING_TYPE 1	# 0 = H-shaped, 1 = omnidirectional
param set-default CA_METHOD 1		# 0 = Pseudo Inverse, 1 = Sequential Desaturation

param set-default CA_ROTOR_COUNT 4
param set-default CA_SV_TL_COUNT 4

param set-default CA_ROTOR0_TILT 1
param set-default CA_SV_TL0_CT 0
param set-default CA_SV_TL0_MAXA 90
param set-default CA_SV_TL0_MINA -90
param set-default CA_SV_TL0_TD 0
param set-default CA_SV0_SLEW 2

param set-default CA_ROTOR1_TILT 2
param set-default CA_SV_TL1_CT 0
param set-default CA_SV_TL1_MAXA 90
param set-default CA_SV_TL1_MINA -90
param set-default CA_SV_TL1_TD 0
param set-default CA_SV1_SLEW 2

param set-default CA_ROTOR2_TILT 3
param set-default CA_SV_TL2_CT 0
param set-default CA_SV_TL2_MAXA 90
param set-default CA_SV_TL2_MINA -90
param set-default CA_SV_TL2_TD 0
param set-default CA_SV2_SLEW 2

param set-default CA_ROTOR3_TILT 4
param set-default CA_SV_TL3_CT 0
param set-default CA_SV_TL3_MAXA 90
param set-default CA_SV_TL3_MINA -90
param set-default CA_SV_TL3_TD 0
param set-default CA_SV3_SLEW 2

param set-default CA_ROTOR0_PX 0.28
param set-default CA_ROTOR0_PY 0.28
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.28
param set-default CA_ROTOR1_PY -0.28
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.28
param set-default CA_ROTOR2_PY -0.28
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.28
param set-default CA_ROTOR3_PY 0.28
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 125
param set-default SIM_GZ_EC_MIN2 125
param set-default SIM_GZ_EC_MIN3 125
param set-default SIM_GZ_EC_MIN4 125

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204

param set-default MPC_THR_HOVER 0.40

