#!/bin/sh
#
# @name Gazebo hillstar rigid arm with tip-mounted gripper
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=hillstar_rigid_arm_gripper}

. ${R}etc/init.d-posix/airframes/4024_gz_hillstar_gripper
